language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - mypy ./streamborne --strict
  - python -m unittest
  - coverage run -m unittest discover test
  - coverage report
  - coverage xml
after_script:
  - codecov
